package com.scalepoint.automation.services.externalapi.ftoggle;

public enum FeatureIds {
    DB_BLOCKING,
    EVOUCHER_BACKEND_SYNCHRONOUS_CALLS,
    NAVISION_MANDATORY_BANK_ACCOUNT_NUMBER,
    NAVISION_MANDATORY_BANK_NAME,
    NAVISION_MANDATORY_BANK_REG_NUMBER,
    NEW_SETTLE_WITHOUT_MAIL_BUTTON,
    SCALEPOINT_HANDLES_VOUCHER_AVAILABLE,
    SHOW_VOUCHER_RIGHT_OF_CANCELLATION,
    USE_ADDRESS2_IN_ORDER_XML_EMAIL,
    USE_BING_MAPS_FOR_DISTANCES,
    USE_CELL_PHONE_IN_ORDER_XML_EMAIL,
    USE_EXTENDED_PRODUCT_VALIDATION,
    USE_IP1_ENCODING_FIX,
    USE_NEW_CATEGORY_MASTER_MESSAGE,
    USE_REDEEM_INPUT_VALIDATION,
    USE_USERS_CACHE,
    XFEEDS_IMPORT_DISABLED,
    COPY_NOTE_BUTTON
}
